name: repo-sync

on:
  schedule:
  - cron:  "0 8 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: sync repo to breanch
      uses: repo-sync/github-sync@v2
      with:
        source_repo: https://github.com/blockscout/blockscout
        source_branch: master
        destination_branch: sync-upstream
        github_token: ${{ secrets.REPO_SYNC_PAT }}
    - name: create pull request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: sync-upstream
        destination_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Sync with upstream"
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "crypto-facs,WilliamXieCrypto,mofhusseini"
        pr_assignee: "crypto-facs,WilliamXieCrypto,mofhusseini"
        pr_label: "auto-pr"
